#!/bin/bash
# ==============================================================================
# sf-hook.sh - Salesforce検証フック (pre-push) の有効化スクリプト
# ------------------------------------------------------------------------------
# [処理概要]
#   1. カレントプロジェクトが Git 管理下の force-* ディレクトリか確認
#   2. .git/hooks/pre-push を強制的に上書き生成
#   3. $HOME/sf-tools/hooks/pre-push を呼び出す構成にする
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. 共通ライブラリの必須設定
# ------------------------------------------------------------------------------
readonly SCRIPT_NAME=$(basename "$0" .sh)
readonly LOG_FILE="./logs/${SCRIPT_NAME}.log"
readonly LOG_MODE="NEW"         # 実行のたびにログをリセット
readonly SILENT_EXEC=1          # コマンドの標準出力はログファイルのみに記録

# ------------------------------------------------------------------------------
# 2. 共通ライブラリの読み込み
# ------------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMON_LIB="${SCRIPT_DIR}/lib/common.sh"

if [[ ! -f "$COMMON_LIB" ]]; then
    echo "[FATAL ERROR] Library not found: $COMMON_LIB" >&2
    exit 1
fi
source "$COMMON_LIB"

# ------------------------------------------------------------------------------
# 3. 定数定義
# ------------------------------------------------------------------------------
readonly HOOK_DEST=".git/hooks/pre-push"
readonly HOOK_MARKER="# Generated by sf-tools: wrapper for pre-push hook"
readonly ACTUAL_HOOK_PATH='${HOME}/sf-tools/hooks/pre-push'

# ------------------------------------------------------------------------------
# 4. 各作業フェーズの定義
# ------------------------------------------------------------------------------

# 【CHECKフェーズ】ディレクトリの検証
phase_check_environment() {
    log "INFO" "CHECK" "実行環境を確認中..."

    # プロジェクトディレクトリ確認
    check_force_dir || die "このスクリプトは 'force-*' ディレクトリ内でのみ実行可能です。" 

    # .git ディレクトリの存在確認
    if [[ ! -d ".git" ]]; then
        die "Gitリポジトリのルートで実行してください（.git ディレクトリが見つかりません）。" 
    fi

    return $RET_OK
}

# 【INSTALLフェーズ】ラッパースクリプトの強制生成
phase_install_hook() {
    log "INFO" "INSTALL" "Git Hook を生成（強制上書き）中..." 

    # hooksディレクトリの存在保証
    mkdir -p "$(dirname "$HOOK_DEST")" 

    # ラッパースクリプトの書き込み (既存ファイルは上書き)
    cat << EOF > "$HOOK_DEST"
#!/bin/bash
$HOOK_MARKER

# sf-tools の実体スクリプトへのパス
HOOK_SCRIPT="$ACTUAL_HOOK_PATH"

if [ -f "\$HOOK_SCRIPT" ]; then
    # 実体が存在すれば実行し、その終了コードをそのままGitに返す
    bash "\$HOOK_SCRIPT" "\$@"
    exit \$?
else
    echo "⚠️ [PRE-PUSH] sf-tools のフックスクリプトが見つかりません: \$HOOK_SCRIPT" >&2
    echo "検証をスキップして Push を継続します。" >&2
    exit 0
fi
EOF

    # 実行権限の付与
    run "INSTALL" chmod +x "$HOOK_DEST" 
}

# ------------------------------------------------------------------------------
# 5. メイン実行フロー
# ------------------------------------------------------------------------------
log "HEADER" "" "Git Hook (pre-push) の有効化を開始します" 

phase_check_environment || die "初期チェックに失敗しました。" 
log "SUCCESS" "CHECK" "環境確認完了。" 

phase_install_hook || die "フックのインストールに失敗しました。" 
log "SUCCESS" "INSTALL" "完了: pre-push フックを強制適用しました。" 

echo "-------------------------------------------------------"
log "INFO" "NOTE" "次回以降の git push 時に自動的に検証が実行されます。" 
log "HEADER" "" "✅ セットアップが完了しました" 

exit $RET_OK