#!/bin/bash
# ==============================================================================
# test_sf-unhook.sh - sf-unhook.sh のテスト
# ==============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/test_helper.sh"
echo -e "${CLR_HEAD}=== sf-unhook.sh ===${CLR_RST}"

SF_HOOK_MARKER="# Generated by sf-tools: wrapper for pre-push hook"

# フックファイルが存在しない場合 → 正常終了
test_no_hook() {
    local td mb
    td=$(setup_force_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    local out; out=$(cd "$td" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-unhook.sh" 2>&1)
    local ec=$?

    assert_exit_ok $ec "フックなし → 正常終了"
    assert_file_not_exists "$td/.git/hooks/pre-push" "フックファイルは存在しない"
    teardown "$td" "$mb"
}

# sf-hook.sh でインストールしたフック → 削除される
test_hook_installed_by_sf_hook() {
    local td mb mh
    td=$(setup_force_dir); mb=$(setup_mock_bin); mh=$(setup_mock_home)
    export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    cd "$td" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-hook.sh" >/dev/null 2>&1
    local out; out=$(cd "$td" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-unhook.sh" 2>&1)
    local ec=$?

    assert_exit_ok $ec "sf-hook.sh で入れたフック → 正常終了"
    assert_file_not_exists "$td/.git/hooks/pre-push" "sf-hook.sh で入れたフックが削除された"
    teardown "$td" "$mb" "$mh"
}

# sf-tools が管理するフック → 削除される
test_sf_tools_hook() {
    local td mb
    td=$(setup_force_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    printf '#!/bin/bash\n%s\n' "$SF_HOOK_MARKER" > "$td/.git/hooks/pre-push"
    chmod +x "$td/.git/hooks/pre-push"

    local out; out=$(cd "$td" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-unhook.sh" 2>&1)
    local ec=$?

    assert_exit_ok $ec "sf-tools フック → 正常終了"
    assert_file_not_exists "$td/.git/hooks/pre-push" "フックファイルが削除された"
    teardown "$td" "$mb"
}

# sf-tools が管理しないフック → 保持される（誤削除防止）
test_external_hook() {
    local td mb
    td=$(setup_force_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    echo '#!/bin/bash' > "$td/.git/hooks/pre-push"
    echo 'echo "external hook"' >> "$td/.git/hooks/pre-push"
    chmod +x "$td/.git/hooks/pre-push"

    local out; out=$(cd "$td" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-unhook.sh" 2>&1)
    local ec=$?

    assert_exit_ok $ec "外部フック → 正常終了（スキップ）"
    assert_file_exists "$td/.git/hooks/pre-push" "外部フックは削除されない"
    teardown "$td" "$mb"
}

# force-* 以外のディレクトリで実行 → 非ゼロ終了
test_outside_force_dir() {
    local rd mb
    rd=$(setup_regular_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    local out; out=$(cd "$rd" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-unhook.sh" 2>&1)
    local ec=$?

    assert_exit_fail $ec "force-* 外 → エラー終了"
    teardown "$rd" "$mb"
}

test_no_hook
test_hook_installed_by_sf_hook
test_sf_tools_hook
test_external_hook
test_outside_force_dir

print_summary
