#!/bin/bash
# ==============================================================================
# test_sf-hook.sh - sf-hook.sh のテスト
# ==============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/test_helper.sh"
echo -e "${CLR_HEAD}=== sf-hook.sh ===${CLR_RST}"

SF_HOOK_MARKER="# Generated by sf-tools: wrapper for pre-push hook"

# 正常インストール → ファイルがコピーされ実行権限がある
test_install_hook() {
    local td mb mh
    setup_std_env td mb mh
    create_all_mocks "$mb"

    local out; out=$(cd "$td" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/bin/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_ok $ec "正常インストール → 終了コード 0"
    assert_file_exists "$td/.git/hooks/pre-push" "pre-push フックがコピーされた"
    assert_executable "$td/.git/hooks/pre-push" "実行権限が付与された"
    assert_file_contains "$td/.git/hooks/pre-push" "$SF_HOOK_MARKER" "コピーされたフックに管理マーカーが含まれる"
    teardown "$td" "$mb" "$mh"
}

# コピーされたフックの内容がコピー元と一致する
test_hook_content_matches_source() {
    local td mb mh
    setup_std_env td mb mh
    create_all_mocks "$mb"

    cd "$td" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/bin/sf-hook.sh" 2>&1 >/dev/null

    local src_content; src_content=$(cat "$mh/sf-tools/hooks/pre-push")
    local dst_content; dst_content=$(cat "$td/.git/hooks/pre-push")
    assert_equals "$src_content" "$dst_content" "コピー内容がコピー元と一致する"
    teardown "$td" "$mb" "$mh"
}

# コピーされたフックが sf-prepush.sh を参照している
test_hook_calls_sf_prepush() {
    local td mb mh
    setup_std_env td mb mh
    create_all_mocks "$mb"

    cd "$td" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/bin/sf-hook.sh" 2>&1 >/dev/null

    assert_file_contains "$td/.git/hooks/pre-push" "sf-prepush.sh" "sf-prepush.sh への参照が含まれる"
    teardown "$td" "$mb" "$mh"
}

# 既存フックを上書きできる
test_overwrite_existing_hook() {
    local td mb mh
    setup_std_env td mb mh
    create_all_mocks "$mb"

    echo "#!/bin/bash" > "$td/.git/hooks/pre-push"
    echo "echo old_hook" >> "$td/.git/hooks/pre-push"

    local out; out=$(cd "$td" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/bin/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_ok $ec "上書きインストール → 終了コード 0"
    assert_file_contains "$td/.git/hooks/pre-push" "sf-prepush.sh" "上書き後に sf-prepush.sh への参照が含まれる"
    teardown "$td" "$mb" "$mh"
}

# コピー元フックが存在しない → エラー
test_no_hook_source() {
    local td mb mh
    setup_std_env td mb mh
    create_all_mocks "$mb"
    rm -f "$mh/sf-tools/hooks/pre-push"

    local out; out=$(cd "$td" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/bin/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_fail $ec "コピー元なし → エラー終了"
    teardown "$td" "$mb" "$mh"
}

# force-* 以外で実行 → エラー
test_outside_force_dir() {
    local rd mb mh
    rd=$(setup_regular_dir); mb=$(setup_mock_bin); mh=$(setup_mock_home)
    export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    local out; out=$(cd "$rd" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/bin/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_fail $ec "force-* 外 → エラー終了"
    teardown "$rd" "$mb" "$mh"
}

# .git ディレクトリが存在しない → エラー
test_no_git_dir() {
    local td mb mh
    setup_std_env td mb mh
    create_all_mocks "$mb"
    rm -rf "$td/.git"

    local out; out=$(cd "$td" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/bin/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_fail $ec ".git なし → エラー終了"
    teardown "$td" "$mb" "$mh"
}

# hooksPath が .husky 系に設定されている → 自動削除してインストール成功
test_fix_husky_hooks_path() {
    local td mb mh
    setup_std_env td mb mh
    create_all_mocks "$mb"

    # .git/config に hooksPath = .husky/_ を仕込む
    git -C "$td" config core.hooksPath ".husky/_"

    local out; out=$(cd "$td" && HOME="$mh" PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/bin/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_ok $ec "hooksPath=.husky/_ でも正常終了"
    local remaining
    remaining=$(git -C "$td" config core.hooksPath 2>/dev/null)
    [[ -z "$remaining" ]] \
        && pass "core.hooksPath が削除された" \
        || fail "core.hooksPath が削除された" "残存値: $remaining"
    assert_file_exists "$td/.git/hooks/pre-push" "hooksPath 削除後にフックがコピーされた"
    teardown "$td" "$mb" "$mh"
}

test_install_hook
test_hook_content_matches_source
test_hook_calls_sf_prepush
test_overwrite_existing_hook
test_no_hook_source
test_fix_husky_hooks_path
test_outside_force_dir
test_no_git_dir

print_summary
