#!/bin/bash
# ==============================================================================
# test_sf-hook.sh - sf-hook.sh のテスト
# ==============================================================================
source "$(dirname "${BASH_SOURCE[0]}")/test_helper.sh"
echo -e "${CLR_HEAD}=== sf-hook.sh ===${CLR_RST}"

SF_HOOK_MARKER="# Generated by sf-tools: wrapper for pre-push hook"

# 正常インストール → ファイルが生成され実行権限がある
test_install_hook() {
    local td mb
    td=$(setup_force_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    local out; out=$(cd "$td" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_ok $ec "正常インストール → 終了コード 0"
    assert_file_exists "$td/.git/hooks/pre-push" "pre-push フックが生成された"
    assert_executable "$td/.git/hooks/pre-push" "実行権限が付与された"
    teardown "$td" "$mb"
}

# 生成されたフックにマーカーが含まれる
test_hook_contains_marker() {
    local td mb
    td=$(setup_force_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    cd "$td" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-hook.sh" 2>&1 >/dev/null

    assert_file_contains "$td/.git/hooks/pre-push" "$SF_HOOK_MARKER" "マーカーが含まれる"
    teardown "$td" "$mb"
}

# 生成されたフックが sf-tools/hooks/pre-push を呼び出す
test_hook_calls_sf_tools() {
    local td mb
    td=$(setup_force_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    cd "$td" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-hook.sh" 2>&1 >/dev/null

    assert_file_contains "$td/.git/hooks/pre-push" "sf-tools/hooks/pre-push" "sf-tools フックへの参照が含まれる"
    teardown "$td" "$mb"
}

# 既存フックを上書きできる
test_overwrite_existing_hook() {
    local td mb
    td=$(setup_force_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    echo "#!/bin/bash" > "$td/.git/hooks/pre-push"
    echo "echo old_hook" >> "$td/.git/hooks/pre-push"

    local out; out=$(cd "$td" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_ok $ec "上書きインストール → 終了コード 0"
    assert_file_contains "$td/.git/hooks/pre-push" "$SF_HOOK_MARKER" "上書き後にマーカーが含まれる"
    teardown "$td" "$mb"
}

# force-* 以外で実行 → エラー
test_outside_force_dir() {
    local rd mb
    rd=$(setup_regular_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"

    local out; out=$(cd "$rd" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_fail $ec "force-* 外 → エラー終了"
    teardown "$rd" "$mb"
}

# .git ディレクトリが存在しない → エラー
test_no_git_dir() {
    local td mb
    td=$(setup_force_dir); mb=$(setup_mock_bin); export MOCK_CALL_LOG="$mb/calls.log"
    create_all_mocks "$mb"
    rm -rf "$td/.git"

    local out; out=$(cd "$td" && PATH="$mb:$PATH" bash "$SF_TOOLS_DIR/sf-hook.sh" 2>&1)
    local ec=$?

    assert_exit_fail $ec ".git なし → エラー終了"
    teardown "$td" "$mb"
}

test_install_hook
test_hook_contains_marker
test_hook_calls_sf_tools
test_overwrite_existing_hook
test_outside_force_dir
test_no_git_dir

print_summary
