# Salesforce マージ順序チェック
name: Salesforce マージ順序チェック

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  call:
    uses: tama-create/sf-tools/.github/workflows/sf-sequence-reusable.yml@main
    with:
      base_ref: ${{ github.event.pull_request.base.ref || github.ref_name }}
      head_ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
      pr_title: ${{ github.event.pull_request.title || '' }}
      pr_number: "${{ github.event.pull_request.number }}"
      pr_url: ${{ github.event.pull_request.html_url || '' }}
      pr_sha: ${{ github.event.pull_request.head.sha || '' }}
    secrets: inherit
